### ISSUE TITLE
current example doesn't work

### ISSUE THREAD

**Issue by thegrumpylion** [readykit/gd#1]
hey there, great initiative!

the provided example breaks.

steps i took

* cloned the repo
* `cd gd/example/src`
* `make`
* `cd ..`
* `godot4 .`

```
Godot Engine v4.0.alpha14.official.106b68050 - https://godotengine.org
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
Vulkan API 1.2.0 - Using Vulkan Device #0: Intel - Intel(R) UHD Graphics (TGL GT1)
../mesa-22.1.7/src/intel/isl/isl.c:2216: FINISHME: ../mesa-22.1.7/src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.
 
SCRIPT ERROR: Parse Error: "HelloWorld" was not found in the current scope.
          at: GDScript::reload (res://Node2D.gd:3)
ERROR: Cannot get class 'ExtendedNode'.
   at: instantiate (core/object/class_db.cpp:325)
WARNING: Node ExtendedNode of type ExtendedNode cannot be created. A placeholder will be created instead.
     at: instantiate (scene/resources/packed_scene.cpp:201)
```

**Comment by Splizard** [comment]
Yep, the package currently requires Godot to be built with  this PR (as mentioned at the top of the Readme, although perhaps I may need to be more clear about this): https://github.com/godotengine/godot/pull/65018

I am hoping to get this merged. In the meantime while I can make some changes so that this package works with Godot master. The new singletons will not be available (gd.DisplayServer, gd.RenderingServer etc) for builds without the required PR.

**Comment by thegrumpylion** [comment]
i totally missed that. will build godot with your patch and try it out.

perhaps having "..requires godot to be build with X" instead of "..requires X" will be more obvious.

thank you for replying.

**Comment by Splizard** [comment]
Updated the Readme!
